# Generated by Django 5.2.6 on 2025-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_name', models.CharField(max_length=50)),
                ('exercise_description', models.TextField()),
                ('exercise_sets', models.PositiveIntegerField(default=3)),
                ('exercise_reps', models.PositiveIntegerField(default=8)),
                ('exercise_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
