# Generated by Django 5.2.6 on 2025-09-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_rest',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
