# Generated by Django 5.2.6 on 2025-09-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
